export const sectors = [
    {name:'Public Administration'},
      {name:'Arts, Entertainment and Recreation'},
      {name:'Education Services / Higher Education'},
      {name:'Health Services / Public Health'},
      {name:'Finance and Insurance'},
      {name:'Information / Media'},
      {name:'Economic / Social Developement'},
      {name:'Security / Police / Peacekeeping'},
      {name:'Disarmament & Demobilization'},
      {name:'Environment'},
      {name:'Private Sector'},
      {name:'Humanitarian - Coordination / Information Management'},
      {name:'Humanitarian - Multiple Clusters'},
      {name:'Humanitarian - Camp Management & Coordination'},
      {name:'Humanitarian - Early Recovery'},
      {name:'Humanitarian - Education'},
      {name:'Humanitarian - Emergency Sheltor'},
      {name:'Humanitarian - Emergency Telecoms'},
      {name:'Humanitarian - Food Security'},
      {name:'Humanitarian - Health'},
      {name:'Humanitarian - Logistics'},
      {name:'Humanitarian - Nutrition'},
      {name:'Humanitarian - Protection'},
      {name:'Humanitarian - Sanitation Water & Hygiene'},
      {name:'Other'}
]